language: php

branches:
  only:
    - master

before_install: ./.travis/before_install.php
install: ./.travis/install.php
script: ./.travis/script.php

matrix:
  include:
    - php: 7.3
      env: SYMFONY_VERSION=5.1.*
    - php: 7.4
      env: SYMFONY_VERSION=5.1.*
    - php: 7.3
      env: SYMFONY_VERSION=5.2.*
    - php: 7.4
      env: SYMFONY_VERSION=5.2.*
